package com.tlys.sys.model;

// Generated 2011-9-20 14:19:26 by Hibernate Tools 3.3.0.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbZbcSysGroup generated by hbm2java
 */
@Entity
@Table(name = "TB_ZBC_SYS_GROUP")
@org.hibernate.annotations.Entity(dynamicUpdate=true,dynamicInsert=true) 
public class SysGroup implements java.io.Serializable {

	private String groupid;
	private String groupname;
	private char isactive;
	private String description;
	private Date createdtime;

	public SysGroup() {
	}

	public SysGroup(String groupid, String groupname, char isactive) {
		this.groupid = groupid;
		this.groupname = groupname;
		this.isactive = isactive;
	}

	public SysGroup(String groupid, String groupname, char isactive,
			String description, Date createdtime) {
		this.groupid = groupid;
		this.groupname = groupname;
		this.isactive = isactive;
		this.description = description;
		this.createdtime = createdtime;
	}

	@Id
	@Column(name = "GROUPID", unique = true, nullable = false, length = 3)
	public String getGroupid() {
		return this.groupid;
	}

	public void setGroupid(String groupid) {
		this.groupid = groupid;
	}

	@Column(name = "GROUPNAME", nullable = false, length = 40)
	public String getGroupname() {
		return this.groupname;
	}

	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}

	@Column(name = "ISACTIVE", nullable = false, length = 1)
	public char getIsactive() {
		return this.isactive;
	}

	public void setIsactive(char isactive) {
		this.isactive = isactive;
	}

	@Column(name = "DESCRIPTION", length = 120)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATEDTIME", length = 7)
	public Date getCreatedtime() {
		return this.createdtime;
	}

	public void setCreatedtime(Date createdtime) {
		this.createdtime = createdtime;
	}

}
