package com.tlys.sys.model;

// Generated 2011-9-20 14:19:26 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import com.tlys.comm.util.CommUtils;

/**
 * TbZbcSysMenuopra generated by hbm2java
 */
@Entity
@Table(name = "TB_ZBC_SYS_MENUOPRA", uniqueConstraints = @UniqueConstraint(columnNames = { "MENUID", "OPERID" }))
public class SysMenuopra implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5198173890707917729L;
	private String opraid;
	private int menuid;
	private String operid;
	private String buttontype;
	private String dbtname;
	private String dispname;
	private String description;
	private String menuopercode;
	private String[] opraids;

	/**
	 * 当前菜单操作类型名称（和operid对应的类型名称) 不参与持久化
	 */
	private String opername;
	/**
	 * 菜单操作按钮显示名称 如果dispname为空，则显示opername
	 */
	private String showname;

	/**
	 * 用于标识当前菜单的此项操作是否被授权给角色，不参与持久化
	 */
	private boolean checked;

	public SysMenuopra() {
	}

	public SysMenuopra(String opraid, int menuid, String operid) {
		this.opraid = opraid;
		this.menuid = menuid;
		this.operid = operid;
	}

	public String getButtontype() {
		return buttontype;
	}

	public String getDbtname() {
		return dbtname;
	}

	public String getDescription() {
		return description;
	}

	public String getDispname() {
		return dispname;
	}

	@Column(name = "MENUID", nullable = false)
	public int getMenuid() {
		return this.menuid;
	}

	public String getMenuopercode() {
		return menuopercode;
	}

	@Column(name = "OPERID", nullable = false, length = 3)
	public String getOperid() {
		return this.operid;
	}

	@Id
	@Column(name = "OPRAID", unique = true, nullable = false, length = 6)
	public String getOpraid() {
		return this.opraid;
	}

	public void setButtontype(String buttontype) {
		this.buttontype = buttontype;
	}

	public void setDbtname(String dbtname) {
		this.dbtname = dbtname;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public void setDispname(String dispname) {
		this.dispname = dispname;
	}

	public void setMenuid(int menuid) {
		this.menuid = menuid;
	}

	public void setMenuopercode(String menuopercode) {
		this.menuopercode = menuopercode;
	}

	public void setOperid(String operid) {
		this.operid = operid;
	}

	public void setOpraid(String opraid) {
		this.opraid = opraid;
	}

	/**
	 * @return the opername
	 */
	@Transient
	public String getOpername() {
		return opername;
	}

	/**
	 * @param opername
	 *            the opername to set
	 */
	public void setOpername(String opername) {
		this.opername = opername;
	}

	/**
	 * @return the showname
	 */
	@Transient
	public String getShowname() {
		if (null == dispname) {
			showname = opername;
		} else {
			showname = dispname;
		}
		return showname;
	}

	/**
	 * @param showname
	 *            the showname to set
	 */
	public void setShowname(String showname) {
		this.showname = showname;
	}

	/**
	 * @return the checked
	 */
	@Transient
	public boolean getChecked() {
		return checked;
	}

	/**
	 * @param checked
	 *            the checked to set
	 */
	public void setChecked(boolean checked) {
		this.checked = checked;
	}

	/**
	 * 重写Object的equals方法，因为将此类放入容器中 将作为两对象相等的方法
	 */
	public boolean equals(Object obj) {
		if (!(obj instanceof SysMenuopra)) {
			return false;
		}
		if (obj == this) {
			return true;
		}
		SysMenuopra otherOp = (SysMenuopra) obj;

		/**
		 * 只要有一个对象的ID值为null，则两个对象就判定为不相等
		 */
		if (otherOp.getOpraid() == null || this.getOpraid() == null)
			return false;

		String s1 = this.getOpraid();
		String s2 = otherOp.getOpraid();

		return s1.equals(s2);
	}

	/**
	 * 使用主键作为hashcode 前提是对象未持久化之前不会使用到此方法
	 */
	public int hashCode() {
		if (this.getOpraid() == null) {
			return 0;
		} else {
			return CommUtils.toInt(this.getOpraid());
		}
	}

	@Transient
	public String[] getOpraids() {
		return opraids;
	}

	public void setOpraids(String[] opraids) {
		this.opraids = opraids;
	}

}
