package com.tlys.sys.model;

// Generated 2011-9-20 14:19:26 by Hibernate Tools 3.3.0.GA

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * TbZbcSysNavimemu generated by hbm2java
 */
@Entity
@Table(name = "TB_ZBC_SYS_NAVIMENU")
@org.hibernate.annotations.Entity(dynamicUpdate = true, dynamicInsert = true)
public class SysNavimenu implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3107935766784699944L;
	private int menuid;
	private String menuname;
	private String urlpath;
	private String iconpath;
	private Integer levelorder;
	private String description;
	private Integer pmenuid;
	// 菜单代码（可能需要通过菜单代码获取菜单，菜单代码不可重复)
	private String menucode;

	/**
	 * add by fengym 当前菜单被授予的操作类型列表 非自DB生成，不参与持久化
	 */
	private List<SysOprationtype> opListSelected;

	/**
	 * add by fengym 当前菜单允许的所有操作类型列表 非自DB生成，不参与持久化
	 */
	private List<SysOprationtype> opListAll;

	/**
	 * 重写Object的equals方法，因为将此类放入容器中 将Menuid作为两对象相等的方法
	 */
	public boolean equals(Object obj) {
		if (!(obj instanceof SysNavimenu)) {
			return false;
		}
		if (obj == this) {
			return true;
		}
		SysNavimenu otherMenu = (SysNavimenu) obj;

		/**
		 * 只要有一个对象的ID值为0，则两个对象就判定为不相等
		 */
		if (otherMenu.getMenuid() == 0)
			return false;

		return otherMenu.getMenuid() == this.getMenuid();
	}

	public String getDescription() {
		return description;
	}

	public String getIconpath() {
		return iconpath;
	}

	public Integer getLevelorder() {
		return levelorder;
	}

	public String getMenucode() {
		return menucode;
	}

	@Id
	@Column(name = "MENUID", unique = true, nullable = false, length = 5)
	public int getMenuid() {
		return menuid;
	}

	public String getMenuname() {
		return menuname;
	}

	/**
	 * @return the opListAll
	 */
	@Transient
	public List<SysOprationtype> getOpListAll() {
		return opListAll;
	}

	/**
	 * @return the opListSelected
	 */
	@Transient
	public List<SysOprationtype> getOpListSelected() {
		return opListSelected;
	}

	public Integer getPmenuid() {
		return pmenuid;
	}

	public String getUrlpath() {
		return urlpath;
	}

	/**
	 * 使用主键作为hashcode 前提是对象未持久化之前不会使用到此方法
	 */
	public int hashCode() {
		return this.menuid;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public void setIconpath(String iconpath) {
		this.iconpath = iconpath;
	}

	public void setLevelorder(Integer levelorder) {
		this.levelorder = levelorder;
	}

	public void setMenucode(String menucode) {
		this.menucode = menucode;
	}

	public void setMenuid(int menuid) {
		this.menuid = menuid;
	}

	public void setMenuname(String menuname) {
		this.menuname = menuname;
	}

	/**
	 * @param opListAll
	 *            the opListAll to set
	 */
	public void setOpListAll(List<SysOprationtype> opListAll) {
		this.opListAll = opListAll;
	}

	/**
	 * @param opListSelected
	 *            the opListSelected to set
	 */
	public void setOpListSelected(List<SysOprationtype> opListSelected) {
		this.opListSelected = opListSelected;
	}

	public void setPmenuid(Integer pmenuid) {
		this.pmenuid = pmenuid;
	}

	public void setUrlpath(String urlpath) {
		this.urlpath = urlpath;
	}

}
