package com.tlys.sys.model;

// Generated 2011-9-20 14:19:26 by Hibernate Tools 3.3.0.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbZbcSysRole generated by hbm2java
 */
@Entity
@Table(name = "TB_ZBC_SYS_ROLE")
@org.hibernate.annotations.Entity(dynamicUpdate=true,dynamicInsert=true) 
public class SysRole implements java.io.Serializable {

	private String roleid;
	private String rolename;
	private char isactive;
	private String description;
	private Date createdtime;

	public SysRole() {
	}

	public SysRole(String roleid, String rolename, char isactive) {
		this.roleid = roleid;
		this.rolename = rolename;
		this.isactive = isactive;
	}

	public SysRole(String roleid, String rolename, char isactive, String description, Date createdtime) {
		this.roleid = roleid;
		this.rolename = rolename;
		this.isactive = isactive;
		this.description = description;
		this.createdtime = createdtime;
	}

	@Column(name = "ROLENAME", nullable = false, length = 40)
	public String getRolename() {
		return this.rolename;
	}

	@Id
	@Column(name = "ROLEID", unique = true, nullable = false, length = 6)
	public String getRoleid() {
		return roleid;
	}

	public void setRoleid(String roleid) {
		this.roleid = roleid;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	@Column(name = "ISACTIVE", nullable = false, length = 1)
	public char getIsactive() {
		return this.isactive;
	}

	public void setIsactive(char isactive) {
		this.isactive = isactive;
	}

	@Column(name = "DESCRIPTION", length = 120)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATEDTIME", length = 7)
	public Date getCreatedtime() {
		return this.createdtime;
	}

	public void setCreatedtime(Date createdtime) {
		this.createdtime = createdtime;
	}
	/**
	 * 重写Object的equals方法，因为将此类放入容器中
	 * 将Menuid作为两对象相等的方法
	 */
	public boolean equals(Object obj) {
		if (!(obj instanceof SysRole)){
			return false;
		}
		if(obj==this){
			return true;
		}
		SysRole sysRole = (SysRole)obj;
		
		/**
		 * 只要有一个对象的ID值为0，则两个对象就判定为不相等
		 */
		if(null == sysRole.getRoleid() || "".equals(sysRole))
			return false;
		
		return sysRole.getRoleid().equals(getRoleid());
	}
	
	/**
	 * 使用主键作为hashcode
	 * 前提是对象未持久化之前不会使用到此方法
	 */
	public int hashCode(){
		return this.roleid.hashCode();
	}
}
