package com.tlys.sys.model;

// Generated 2011-9-20 14:19:26 by Hibernate Tools 3.3.0.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TbZbcSysUserroles generated by hbm2java
 */
@Entity
@Table(name = "TB_ZBC_SYS_USERROLES",  uniqueConstraints = @UniqueConstraint(columnNames = { "USERID", "ROLEID" }))
@org.hibernate.annotations.Entity(dynamicUpdate=true,dynamicInsert=true) 
public class SysUserroles implements java.io.Serializable {

	private int id;
	private String userid;
	private String roleid;
	private Date grantedtime;

	public SysUserroles() {
	}

	public SysUserroles(int id, String userid, String roleid) {
		this.id = id;
		this.userid = userid;
		this.roleid = roleid;
	}

	public SysUserroles(int id, String userid, String roleid, Date grantedtime) {
		this.id = id;
		this.userid = userid;
		this.roleid = roleid;
		this.grantedtime = grantedtime;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 6, scale = 0)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator="oraSeqGenerator") 
	@SequenceGenerator(name="oraSeqGenerator", 
			sequenceName="SEQ_TB_ZBC_SYS_USERROLES", allocationSize=1)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "USERID", nullable = false, length = 6)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	@Column(name = "ROLEID", nullable = false, length = 6)
	public String getRoleid() {
		return roleid;
	}

	public void setRoleid(String roleid) {
		this.roleid = roleid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "GRANTEDTIME", length = 7)
	public Date getGrantedtime() {
		return this.grantedtime;
	}

	public void setGrantedtime(Date grantedtime) {
		this.grantedtime = grantedtime;
	}

}
